# This is a basic workflow to help you get started with Actions

name: py
# on:
#   schedule:
#     - cron: "0 * * * *" #runs at 00:00 UTC everyday
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: execute py script # run the run.py to get the latest data
        run: |
          python data_updater/download_google.py
      - name: show results
        run: echo "Finished"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: google_mobility_australia.csv
          path: dashApp/data/google_mobility_australia.csv
#           - name: export index
#             .... # use crosponding script or actions to help export.
