# This is a basic workflow to help you get started with Actions

name: py
on:
  schedule:
    - cron: "0 * * * *" #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python data_updater/download_google.py
      - name: show results
        run: echo "Finished"
#           - name: export index
#             .... # use crosponding script or actions to help export.
